openapi: "3.0.3"
info:
  description: "Veřejn&#233; API pro v&#253;stup k rozložen&#237; živočichů v ZOO."
  title: "Zoo - API Public"
  version: "1.1.1.0"
tags:
  -
    name: animals
    description: "Operations with Animals."
  -
    name: enclosures
    description: "Operations with Enclosures."
paths:
  /enclosures/{enclosure_id}/animals:
    get:
      tags:
        - enclosures
      summary: Get Animals In Enclosure
      parameters: 
        -
          in: path
          name: enclosure_id
          schema: 
            type: integer
            format: int64
          required: true
      responses: 
        200:
          description: "Successful operation"
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal'
        404:
          description: "Not Found"
  /animals:
    post:
      tags:
        - animals
      summary: Post Animal
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Animal'
      responses: 
        200:
          description: "Successful operation"
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Animal'
  /animals/{animal_id}:
    put:
      tags:
        - animals
      summary: Put Animal Into Enclosure
      parameters: 
        -
          in: path
          name: animal_id
          schema: 
            type: integer
            format: int64
          required: true
        -
          in: query
          name: enclosure_id
          schema: 
            type: integer
            format: int64
          required: true
        -
          in: query
          name: smth
          schema: 
            type: integer
            format: int64
          required: true
      responses: 
        200:
          description: "Successful operation"
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Animal'
components:
  schemas:
    # model/bachelor/test_zoo_app/1.1.1/Zoo - API Public
    #     -> model/bachelor/test_zoo_app/1.1.1/Get Animals In Enclosure
    #     -> model/bachelor/test_zoo_app/1.1.1/Response
    #     -> model/bachelor/test_zoo_app/1.1.1/Response 200
    #     -> model/bachelor/test_zoo_app/1.1.1/schema/Animal
    #     -> model/bachelor/test_zoo_app/1.1.1/schema/Enclosure
    Animal:
      type: object
      properties:
        id:
          type: integer
          format: int64
        Animal Type:
          $ref: '#/components/schemas/AnimalType'
        birthDate:
          type: string
          format: date
        Enclosure:
          $ref: '#/components/schemas/Enclosure'
      required: 
        - id
        - Animal Type
        - birthDate
        - Enclosure
    # model/bachelor/test_zoo_app/1.1.1/Zoo - API Public
    #     -> model/bachelor/test_zoo_app/1.1.1/Get Animals In Enclosure
    #     -> model/bachelor/test_zoo_app/1.1.1/Response
    #     -> model/bachelor/test_zoo_app/1.1.1/Response 200
    #     -> model/bachelor/test_zoo_app/1.1.1/schema/Animal
    #     -> model/bachelor/test_zoo_app/1.1.1/schema/Animal Type
    AnimalType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        species_name:
          type: string
      required: 
        - id
        - species_name
    # model/bachelor/test_zoo_app/1.1.1/Zoo - API Public
    #     -> model/bachelor/test_zoo_app/1.1.1/Get Animals In Enclosure
    #     -> model/bachelor/test_zoo_app/1.1.1/Response
    #     -> model/bachelor/test_zoo_app/1.1.1/Response 200
    #     -> model/bachelor/test_zoo_app/1.1.1/schema/Animal
    #     -> model/bachelor/test_zoo_app/1.1.1/schema/Enclosure
    Enclosure:
      type: object
      properties:
        id:
          type: integer
          format: int64
        Animal:
          $ref: '#/components/schemas/Animal'
      required: 
        - id
        - Animal
