generatorName: spring
apiPackage: cz.cez.col.dummy.v1_0.controller
modelPackage: cz.cez.col.dummy.v1_0.domain
groupId: cz.cez.cpr.dummy
artifactId: dummy
inputSpec: ./export/swagger.yaml
outputDir: output_java
additionalProperties:
  java8: true
  useTags: true
  interfaceOnly: true
  hideGenerationTimestamp: true
  delegatePattern: true
