openapi: "3.0.3"
info:
  title: "Dummy"
  version: "1.0.0"
tags:
  -
    name: dummy
    description: "Dummy"
paths:
  /dummy:
    post:
      tags:
        - dummy
      summary: dummy
      description: "dummy"
      operationId: dummy
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: "dummy"
          content:
            application/pdf:
              schema:
                type: string
                format: binary
